Query updates (#34)
* Update edge to new name: RemoteInteractiveLogonRight

Edge was renamed in a BloodHound update.

* Create Locations of Owned objects - AZ.yml

Similar to the query "Locations of Tier Zero / High-Value objects" for AD

* Create Locations of Owned objects - AD.yml

Similar to the query "Locations of Tier Zero / High-Value objects" for AD

* Fix category: Map Azure Management structure

* Update name from 'Account' to 'Object'

* Update queries to match BloodHound prebuilt query

* Add support for node labels vs legacy system_tags

* Pull in new BloodHound queries

* Add warning to description of many-to-many query

* Update name from 'Account' to 'Object'

* Delete Collection health of specific computer.yml

Query was duplicate of 'All incoming and local paths for a specific computer' - https://queries.specterops.io/?input=1f67e538-19d4-4020-89c8-5b39b31571bd

* address failed test: yaml.scanner.ScannerError: mapping values are not allowed here   in "queries/Shortest paths from Owned objects to Tier Zero.yml", line 6, column 21

* address failed test: Failed: Parsing failed for file queries/Shortest paths to Tier Zero High Value targets.yml: Syntax error at line: 1

* Update combined queries

* Update readme

- Remove unnecessary chars
- Add a BHOP example for testing all queries

* Delete Trace ACE inheritance.yml

The query was unnecessary as an ACE tracing feature is now in-product via the Edge Entity Panel, and this query had limited functionality anyway.

* Update Computers with non-default Primary Group membership.yml - change DC/RODC ID method

Change the identification method for DCs and RODCs to the built-in bool

* Add warning to description of many-to-many queries

* Fixed query: Tier Zero accounts not members of Denied RODC Password Replication Group

Was throwing error on PG: WARNING: 500 - ERROR: missing FROM-clause entry for table "s0" (SQLSTATE 42P01)

* Fix to pass test

FAILED tests/test_cypher_syntax.py::test_cypher_validation[queries/Shortest paths from Azure Applications to Tier Zero High Value targets.yml] - yaml.scanner.ScannerError: mapping values are not allowed here

* Update combined queries

* Update combined queries

---------

Co-authored-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
Co-authored-by: Joey Dreijer <jdreijer@specterops.io>